### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by labpaw**
You are also have a typo at [this line](https://github.com/Indemnity83/irontank/blob/develop/src/main/resources/assets/irontank/lang/en_US.lang#L6). ";" shouldn't be there.

### CODE REVIEW

**Comment by Indemnity83** [comment]
:+1: Thanks!

**Comment by Indemnity83** [comment]
I should have checked before pulling (lesson learned) and I don't know Russian, but just plugging these into google translate and I'm wondering if Железная  should instead be Железо?

**Comment by labpaw** [comment]
You shouldn't check my translation through Google translate (because it's derpy in most cases). I've translated 99% of all translated mods into Russian. I've also translated Buildcraft and IronChest. "Железо"(Iron) is a noun in Russian but "Железная" is a adjective in Russian which is also Iron in English.

**Comment by Indemnity83** [comment]
I meant no offense, I only checked it to make sure it was actually real (wouldn't surprise me if there were people out there who submitted a PR with a false translation just to see if they could get it pulled) and when google spat back 'railroad' I thought I would ask. 

Thanks for the contribution.

**Pull request merged**
